# service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: iris-api
spec:
  type: LoadBalancer
  selector:
    app: iris-api
  ports:
    - port: 80
      targetPort: 8200

# deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
  labels:
    app: iris-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      # if you created a KSA bound to GCP (Workload Identity), put that name here
      serviceAccountName: telemetry-access
      containers:
        - name: iris-api
          image: us-central1-docker.pkg.dev/precise-braid-474114-m3/my-repo/iris-api:v2
          ports:
            - containerPort: 8200
          readinessProbe:
            httpGet:
              path: /ready_check
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /live_check
              port: 8200
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

# hpa.yaml
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-api   
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
